### PR TITLE
Added the project_runfolders.sh script from local_scripts

### PR DESCRIPTION
**Pull request by PerLundmark**
link_project_reports.sh needs the project_runfolders.sh script to function. This PR adds project_runfolders.sh from local_scripts on irma.

### CODE REVIEW

**Review by sarek928 — DISMISSED** [review]
Looks good!

**Comment by matrulda** [comment]
Nice! Could you add a short description of the script (basically the description in the script) to the repo README?

**Comment by PerLundmark** [comment]
Added a short description to the readme

**Review by matrulda — APPROVED** [review]
👍

**Pull request merged**
